openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
paths:
  /api/shorten:
    post:
      summary: Create a shortened URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
                  example: "https://example.com/long-page"
      responses:
        '201':
          description: Short link created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "xy7Z21"
                  shortUrl:
                    type: string
                    example: "/xy7Z21"
                  originalUrl:
                    type: string
                    example: "https://example.com/long-page"
        '400':
          description: Invalid URL provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
